// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"github.com/facebook/ent/dialect/sql"
	"github.com/vicanso/elite/ent/chapter"
)

// Chapter is the model entity for the Chapter schema.
type Chapter struct {
	config `json:"-" sql:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"createdAt,omitempty" sql:"created_at"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updatedAt,omitempty" sql:"updated_at"`
	// Novel holds the value of the "novel" field.
	Novel int `json:"novel,omitempty"`
	// No holds the value of the "no" field.
	No int `json:"no,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// WordCount holds the value of the "word_count" field.
	WordCount int `json:"wordCount,omitempty" sql:"word_count"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Chapter) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullTime{},   // created_at
		&sql.NullTime{},   // updated_at
		&sql.NullInt64{},  // novel
		&sql.NullInt64{},  // no
		&sql.NullString{}, // title
		&sql.NullString{}, // content
		&sql.NullInt64{},  // word_count
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Chapter fields.
func (c *Chapter) assignValues(values ...interface{}) error {
	if m, n := len(values), len(chapter.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	c.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field created_at", values[0])
	} else if value.Valid {
		c.CreatedAt = value.Time
	}
	if value, ok := values[1].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field updated_at", values[1])
	} else if value.Valid {
		c.UpdatedAt = value.Time
	}
	if value, ok := values[2].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field novel", values[2])
	} else if value.Valid {
		c.Novel = int(value.Int64)
	}
	if value, ok := values[3].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field no", values[3])
	} else if value.Valid {
		c.No = int(value.Int64)
	}
	if value, ok := values[4].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field title", values[4])
	} else if value.Valid {
		c.Title = value.String
	}
	if value, ok := values[5].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field content", values[5])
	} else if value.Valid {
		c.Content = value.String
	}
	if value, ok := values[6].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field word_count", values[6])
	} else if value.Valid {
		c.WordCount = int(value.Int64)
	}
	return nil
}

// Update returns a builder for updating this Chapter.
// Note that, you need to call Chapter.Unwrap() before calling this method, if this Chapter
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Chapter) Update() *ChapterUpdateOne {
	return (&ChapterClient{config: c.config}).UpdateOne(c)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (c *Chapter) Unwrap() *Chapter {
	tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: Chapter is not a transactional entity")
	}
	c.config.driver = tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Chapter) String() string {
	var builder strings.Builder
	builder.WriteString("Chapter(")
	builder.WriteString(fmt.Sprintf("id=%v", c.ID))
	builder.WriteString(", created_at=")
	builder.WriteString(c.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", updated_at=")
	builder.WriteString(c.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", novel=")
	builder.WriteString(fmt.Sprintf("%v", c.Novel))
	builder.WriteString(", no=")
	builder.WriteString(fmt.Sprintf("%v", c.No))
	builder.WriteString(", title=")
	builder.WriteString(c.Title)
	builder.WriteString(", content=")
	builder.WriteString(c.Content)
	builder.WriteString(", word_count=")
	builder.WriteString(fmt.Sprintf("%v", c.WordCount))
	builder.WriteByte(')')
	return builder.String()
}

// Chapters is a parsable slice of Chapter.
type Chapters []*Chapter

func (c Chapters) config(cfg config) {
	for _i := range c {
		c[_i].config = cfg
	}
}
