// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/vicanso/elite/ent/novel"
	"github.com/vicanso/elite/ent/predicate"
)

// NovelUpdate is the builder for updating Novel entities.
type NovelUpdate struct {
	config
	hooks      []Hook
	mutation   *NovelMutation
	predicates []predicate.Novel
}

// Where adds a new predicate for the builder.
func (nu *NovelUpdate) Where(ps ...predicate.Novel) *NovelUpdate {
	nu.predicates = append(nu.predicates, ps...)
	return nu
}

// SetStatus sets the status field.
func (nu *NovelUpdate) SetStatus(i int) *NovelUpdate {
	nu.mutation.ResetStatus()
	nu.mutation.SetStatus(i)
	return nu
}

// SetNillableStatus sets the status field if the given value is not nil.
func (nu *NovelUpdate) SetNillableStatus(i *int) *NovelUpdate {
	if i != nil {
		nu.SetStatus(*i)
	}
	return nu
}

// AddStatus adds i to status.
func (nu *NovelUpdate) AddStatus(i int) *NovelUpdate {
	nu.mutation.AddStatus(i)
	return nu
}

// SetCover sets the cover field.
func (nu *NovelUpdate) SetCover(s string) *NovelUpdate {
	nu.mutation.SetCover(s)
	return nu
}

// SetNillableCover sets the cover field if the given value is not nil.
func (nu *NovelUpdate) SetNillableCover(s *string) *NovelUpdate {
	if s != nil {
		nu.SetCover(*s)
	}
	return nu
}

// ClearCover clears the value of cover.
func (nu *NovelUpdate) ClearCover() *NovelUpdate {
	nu.mutation.ClearCover()
	return nu
}

// SetSummary sets the summary field.
func (nu *NovelUpdate) SetSummary(s string) *NovelUpdate {
	nu.mutation.SetSummary(s)
	return nu
}

// Mutation returns the NovelMutation object of the builder.
func (nu *NovelUpdate) Mutation() *NovelMutation {
	return nu.mutation
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (nu *NovelUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	nu.defaults()
	if len(nu.hooks) == 0 {
		if err = nu.check(); err != nil {
			return 0, err
		}
		affected, err = nu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NovelMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = nu.check(); err != nil {
				return 0, err
			}
			nu.mutation = mutation
			affected, err = nu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(nu.hooks) - 1; i >= 0; i-- {
			mut = nu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, nu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (nu *NovelUpdate) SaveX(ctx context.Context) int {
	affected, err := nu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (nu *NovelUpdate) Exec(ctx context.Context) error {
	_, err := nu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nu *NovelUpdate) ExecX(ctx context.Context) {
	if err := nu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nu *NovelUpdate) defaults() {
	if _, ok := nu.mutation.UpdatedAt(); !ok {
		v := novel.UpdateDefaultUpdatedAt()
		nu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nu *NovelUpdate) check() error {
	if v, ok := nu.mutation.Status(); ok {
		if err := novel.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf("ent: validator failed for field \"status\": %w", err)}
		}
	}
	return nil
}

func (nu *NovelUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   novel.Table,
			Columns: novel.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: novel.FieldID,
			},
		},
	}
	if ps := nu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nu.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: novel.FieldUpdatedAt,
		})
	}
	if value, ok := nu.mutation.Status(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: novel.FieldStatus,
		})
	}
	if value, ok := nu.mutation.AddedStatus(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: novel.FieldStatus,
		})
	}
	if value, ok := nu.mutation.Cover(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: novel.FieldCover,
		})
	}
	if nu.mutation.CoverCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: novel.FieldCover,
		})
	}
	if value, ok := nu.mutation.Summary(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: novel.FieldSummary,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, nu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{novel.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// NovelUpdateOne is the builder for updating a single Novel entity.
type NovelUpdateOne struct {
	config
	hooks    []Hook
	mutation *NovelMutation
}

// SetStatus sets the status field.
func (nuo *NovelUpdateOne) SetStatus(i int) *NovelUpdateOne {
	nuo.mutation.ResetStatus()
	nuo.mutation.SetStatus(i)
	return nuo
}

// SetNillableStatus sets the status field if the given value is not nil.
func (nuo *NovelUpdateOne) SetNillableStatus(i *int) *NovelUpdateOne {
	if i != nil {
		nuo.SetStatus(*i)
	}
	return nuo
}

// AddStatus adds i to status.
func (nuo *NovelUpdateOne) AddStatus(i int) *NovelUpdateOne {
	nuo.mutation.AddStatus(i)
	return nuo
}

// SetCover sets the cover field.
func (nuo *NovelUpdateOne) SetCover(s string) *NovelUpdateOne {
	nuo.mutation.SetCover(s)
	return nuo
}

// SetNillableCover sets the cover field if the given value is not nil.
func (nuo *NovelUpdateOne) SetNillableCover(s *string) *NovelUpdateOne {
	if s != nil {
		nuo.SetCover(*s)
	}
	return nuo
}

// ClearCover clears the value of cover.
func (nuo *NovelUpdateOne) ClearCover() *NovelUpdateOne {
	nuo.mutation.ClearCover()
	return nuo
}

// SetSummary sets the summary field.
func (nuo *NovelUpdateOne) SetSummary(s string) *NovelUpdateOne {
	nuo.mutation.SetSummary(s)
	return nuo
}

// Mutation returns the NovelMutation object of the builder.
func (nuo *NovelUpdateOne) Mutation() *NovelMutation {
	return nuo.mutation
}

// Save executes the query and returns the updated entity.
func (nuo *NovelUpdateOne) Save(ctx context.Context) (*Novel, error) {
	var (
		err  error
		node *Novel
	)
	nuo.defaults()
	if len(nuo.hooks) == 0 {
		if err = nuo.check(); err != nil {
			return nil, err
		}
		node, err = nuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NovelMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = nuo.check(); err != nil {
				return nil, err
			}
			nuo.mutation = mutation
			node, err = nuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(nuo.hooks) - 1; i >= 0; i-- {
			mut = nuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, nuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (nuo *NovelUpdateOne) SaveX(ctx context.Context) *Novel {
	node, err := nuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (nuo *NovelUpdateOne) Exec(ctx context.Context) error {
	_, err := nuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nuo *NovelUpdateOne) ExecX(ctx context.Context) {
	if err := nuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nuo *NovelUpdateOne) defaults() {
	if _, ok := nuo.mutation.UpdatedAt(); !ok {
		v := novel.UpdateDefaultUpdatedAt()
		nuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nuo *NovelUpdateOne) check() error {
	if v, ok := nuo.mutation.Status(); ok {
		if err := novel.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf("ent: validator failed for field \"status\": %w", err)}
		}
	}
	return nil
}

func (nuo *NovelUpdateOne) sqlSave(ctx context.Context) (_node *Novel, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   novel.Table,
			Columns: novel.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: novel.FieldID,
			},
		},
	}
	id, ok := nuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Novel.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := nuo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: novel.FieldUpdatedAt,
		})
	}
	if value, ok := nuo.mutation.Status(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: novel.FieldStatus,
		})
	}
	if value, ok := nuo.mutation.AddedStatus(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: novel.FieldStatus,
		})
	}
	if value, ok := nuo.mutation.Cover(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: novel.FieldCover,
		})
	}
	if nuo.mutation.CoverCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: novel.FieldCover,
		})
	}
	if value, ok := nuo.mutation.Summary(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: novel.FieldSummary,
		})
	}
	_node = &Novel{config: nuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues()
	if err = sqlgraph.UpdateNode(ctx, nuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{novel.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
