// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/vicanso/elite/ent/novelsource"
	"github.com/vicanso/elite/ent/predicate"
)

// NovelSourceQuery is the builder for querying NovelSource entities.
type NovelSourceQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	unique     []string
	predicates []predicate.NovelSource
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the builder.
func (nsq *NovelSourceQuery) Where(ps ...predicate.NovelSource) *NovelSourceQuery {
	nsq.predicates = append(nsq.predicates, ps...)
	return nsq
}

// Limit adds a limit step to the query.
func (nsq *NovelSourceQuery) Limit(limit int) *NovelSourceQuery {
	nsq.limit = &limit
	return nsq
}

// Offset adds an offset step to the query.
func (nsq *NovelSourceQuery) Offset(offset int) *NovelSourceQuery {
	nsq.offset = &offset
	return nsq
}

// Order adds an order step to the query.
func (nsq *NovelSourceQuery) Order(o ...OrderFunc) *NovelSourceQuery {
	nsq.order = append(nsq.order, o...)
	return nsq
}

// First returns the first NovelSource entity in the query. Returns *NotFoundError when no novelsource was found.
func (nsq *NovelSourceQuery) First(ctx context.Context) (*NovelSource, error) {
	nodes, err := nsq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{novelsource.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (nsq *NovelSourceQuery) FirstX(ctx context.Context) *NovelSource {
	node, err := nsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first NovelSource id in the query. Returns *NotFoundError when no id was found.
func (nsq *NovelSourceQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = nsq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{novelsource.Label}
		return
	}
	return ids[0], nil
}

// FirstXID is like FirstID, but panics if an error occurs.
func (nsq *NovelSourceQuery) FirstXID(ctx context.Context) int {
	id, err := nsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only NovelSource entity in the query, returns an error if not exactly one entity was returned.
func (nsq *NovelSourceQuery) Only(ctx context.Context) (*NovelSource, error) {
	nodes, err := nsq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{novelsource.Label}
	default:
		return nil, &NotSingularError{novelsource.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (nsq *NovelSourceQuery) OnlyX(ctx context.Context) *NovelSource {
	node, err := nsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID returns the only NovelSource id in the query, returns an error if not exactly one id was returned.
func (nsq *NovelSourceQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = nsq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{novelsource.Label}
	default:
		err = &NotSingularError{novelsource.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (nsq *NovelSourceQuery) OnlyIDX(ctx context.Context) int {
	id, err := nsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of NovelSources.
func (nsq *NovelSourceQuery) All(ctx context.Context) ([]*NovelSource, error) {
	if err := nsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return nsq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (nsq *NovelSourceQuery) AllX(ctx context.Context) []*NovelSource {
	nodes, err := nsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of NovelSource ids.
func (nsq *NovelSourceQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := nsq.Select(novelsource.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (nsq *NovelSourceQuery) IDsX(ctx context.Context) []int {
	ids, err := nsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (nsq *NovelSourceQuery) Count(ctx context.Context) (int, error) {
	if err := nsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return nsq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (nsq *NovelSourceQuery) CountX(ctx context.Context) int {
	count, err := nsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (nsq *NovelSourceQuery) Exist(ctx context.Context) (bool, error) {
	if err := nsq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return nsq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (nsq *NovelSourceQuery) ExistX(ctx context.Context) bool {
	exist, err := nsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (nsq *NovelSourceQuery) Clone() *NovelSourceQuery {
	return &NovelSourceQuery{
		config:     nsq.config,
		limit:      nsq.limit,
		offset:     nsq.offset,
		order:      append([]OrderFunc{}, nsq.order...),
		unique:     append([]string{}, nsq.unique...),
		predicates: append([]predicate.NovelSource{}, nsq.predicates...),
		// clone intermediate query.
		sql:  nsq.sql.Clone(),
		path: nsq.path,
	}
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"createdAt,omitempty" sql:"created_at"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.NovelSource.Query().
//		GroupBy(novelsource.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (nsq *NovelSourceQuery) GroupBy(field string, fields ...string) *NovelSourceGroupBy {
	group := &NovelSourceGroupBy{config: nsq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := nsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return nsq.sqlQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"createdAt,omitempty" sql:"created_at"`
//	}
//
//	client.NovelSource.Query().
//		Select(novelsource.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (nsq *NovelSourceQuery) Select(field string, fields ...string) *NovelSourceSelect {
	selector := &NovelSourceSelect{config: nsq.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := nsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return nsq.sqlQuery(), nil
	}
	return selector
}

func (nsq *NovelSourceQuery) prepareQuery(ctx context.Context) error {
	if nsq.path != nil {
		prev, err := nsq.path(ctx)
		if err != nil {
			return err
		}
		nsq.sql = prev
	}
	return nil
}

func (nsq *NovelSourceQuery) sqlAll(ctx context.Context) ([]*NovelSource, error) {
	var (
		nodes = []*NovelSource{}
		_spec = nsq.querySpec()
	)
	_spec.ScanValues = func() []interface{} {
		node := &NovelSource{config: nsq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, nsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (nsq *NovelSourceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := nsq.querySpec()
	return sqlgraph.CountNodes(ctx, nsq.driver, _spec)
}

func (nsq *NovelSourceQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := nsq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (nsq *NovelSourceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   novelsource.Table,
			Columns: novelsource.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: novelsource.FieldID,
			},
		},
		From:   nsq.sql,
		Unique: true,
	}
	if ps := nsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := nsq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := nsq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := nsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector, novelsource.ValidColumn)
			}
		}
	}
	return _spec
}

func (nsq *NovelSourceQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(nsq.driver.Dialect())
	t1 := builder.Table(novelsource.Table)
	selector := builder.Select(t1.Columns(novelsource.Columns...)...).From(t1)
	if nsq.sql != nil {
		selector = nsq.sql
		selector.Select(selector.Columns(novelsource.Columns...)...)
	}
	for _, p := range nsq.predicates {
		p(selector)
	}
	for _, p := range nsq.order {
		p(selector, novelsource.ValidColumn)
	}
	if offset := nsq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := nsq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// NovelSourceGroupBy is the builder for group-by NovelSource entities.
type NovelSourceGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (nsgb *NovelSourceGroupBy) Aggregate(fns ...AggregateFunc) *NovelSourceGroupBy {
	nsgb.fns = append(nsgb.fns, fns...)
	return nsgb
}

// Scan applies the group-by query and scan the result into the given value.
func (nsgb *NovelSourceGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := nsgb.path(ctx)
	if err != nil {
		return err
	}
	nsgb.sql = query
	return nsgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (nsgb *NovelSourceGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := nsgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (nsgb *NovelSourceGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(nsgb.fields) > 1 {
		return nil, errors.New("ent: NovelSourceGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := nsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (nsgb *NovelSourceGroupBy) StringsX(ctx context.Context) []string {
	v, err := nsgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from group-by. It is only allowed when querying group-by with one field.
func (nsgb *NovelSourceGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = nsgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{novelsource.Label}
	default:
		err = fmt.Errorf("ent: NovelSourceGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (nsgb *NovelSourceGroupBy) StringX(ctx context.Context) string {
	v, err := nsgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (nsgb *NovelSourceGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(nsgb.fields) > 1 {
		return nil, errors.New("ent: NovelSourceGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := nsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (nsgb *NovelSourceGroupBy) IntsX(ctx context.Context) []int {
	v, err := nsgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from group-by. It is only allowed when querying group-by with one field.
func (nsgb *NovelSourceGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = nsgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{novelsource.Label}
	default:
		err = fmt.Errorf("ent: NovelSourceGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (nsgb *NovelSourceGroupBy) IntX(ctx context.Context) int {
	v, err := nsgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (nsgb *NovelSourceGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(nsgb.fields) > 1 {
		return nil, errors.New("ent: NovelSourceGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := nsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (nsgb *NovelSourceGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := nsgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from group-by. It is only allowed when querying group-by with one field.
func (nsgb *NovelSourceGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = nsgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{novelsource.Label}
	default:
		err = fmt.Errorf("ent: NovelSourceGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (nsgb *NovelSourceGroupBy) Float64X(ctx context.Context) float64 {
	v, err := nsgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (nsgb *NovelSourceGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(nsgb.fields) > 1 {
		return nil, errors.New("ent: NovelSourceGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := nsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (nsgb *NovelSourceGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := nsgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from group-by. It is only allowed when querying group-by with one field.
func (nsgb *NovelSourceGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = nsgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{novelsource.Label}
	default:
		err = fmt.Errorf("ent: NovelSourceGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (nsgb *NovelSourceGroupBy) BoolX(ctx context.Context) bool {
	v, err := nsgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (nsgb *NovelSourceGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range nsgb.fields {
		if !novelsource.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := nsgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := nsgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (nsgb *NovelSourceGroupBy) sqlQuery() *sql.Selector {
	selector := nsgb.sql
	columns := make([]string, 0, len(nsgb.fields)+len(nsgb.fns))
	columns = append(columns, nsgb.fields...)
	for _, fn := range nsgb.fns {
		columns = append(columns, fn(selector, novelsource.ValidColumn))
	}
	return selector.Select(columns...).GroupBy(nsgb.fields...)
}

// NovelSourceSelect is the builder for select fields of NovelSource entities.
type NovelSourceSelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Scan applies the selector query and scan the result into the given value.
func (nss *NovelSourceSelect) Scan(ctx context.Context, v interface{}) error {
	query, err := nss.path(ctx)
	if err != nil {
		return err
	}
	nss.sql = query
	return nss.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (nss *NovelSourceSelect) ScanX(ctx context.Context, v interface{}) {
	if err := nss.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (nss *NovelSourceSelect) Strings(ctx context.Context) ([]string, error) {
	if len(nss.fields) > 1 {
		return nil, errors.New("ent: NovelSourceSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := nss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (nss *NovelSourceSelect) StringsX(ctx context.Context) []string {
	v, err := nss.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from selector. It is only allowed when selecting one field.
func (nss *NovelSourceSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = nss.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{novelsource.Label}
	default:
		err = fmt.Errorf("ent: NovelSourceSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (nss *NovelSourceSelect) StringX(ctx context.Context) string {
	v, err := nss.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (nss *NovelSourceSelect) Ints(ctx context.Context) ([]int, error) {
	if len(nss.fields) > 1 {
		return nil, errors.New("ent: NovelSourceSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := nss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (nss *NovelSourceSelect) IntsX(ctx context.Context) []int {
	v, err := nss.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from selector. It is only allowed when selecting one field.
func (nss *NovelSourceSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = nss.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{novelsource.Label}
	default:
		err = fmt.Errorf("ent: NovelSourceSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (nss *NovelSourceSelect) IntX(ctx context.Context) int {
	v, err := nss.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (nss *NovelSourceSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(nss.fields) > 1 {
		return nil, errors.New("ent: NovelSourceSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := nss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (nss *NovelSourceSelect) Float64sX(ctx context.Context) []float64 {
	v, err := nss.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from selector. It is only allowed when selecting one field.
func (nss *NovelSourceSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = nss.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{novelsource.Label}
	default:
		err = fmt.Errorf("ent: NovelSourceSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (nss *NovelSourceSelect) Float64X(ctx context.Context) float64 {
	v, err := nss.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (nss *NovelSourceSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(nss.fields) > 1 {
		return nil, errors.New("ent: NovelSourceSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := nss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (nss *NovelSourceSelect) BoolsX(ctx context.Context) []bool {
	v, err := nss.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from selector. It is only allowed when selecting one field.
func (nss *NovelSourceSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = nss.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{novelsource.Label}
	default:
		err = fmt.Errorf("ent: NovelSourceSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (nss *NovelSourceSelect) BoolX(ctx context.Context) bool {
	v, err := nss.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (nss *NovelSourceSelect) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range nss.fields {
		if !novelsource.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for selection", f)}
		}
	}
	rows := &sql.Rows{}
	query, args := nss.sqlQuery().Query()
	if err := nss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (nss *NovelSourceSelect) sqlQuery() sql.Querier {
	selector := nss.sql
	selector.Select(selector.Columns(nss.fields...)...)
	return selector
}
