app: elite
requestLimit: 1024
# apiPrefix: /api
listen: ":7001"

# cookie track key
track: jt


# redis 配置(pass从env中获取pass这个配置为密码，如果未配置则为空)
redis: redis://127.0.0.1:6379

# postgres 配置 (pass从env中获取pass这个配置为密码，如果未配置则为空)
postgres:
  host: 127.0.0.1
  port: 5432
  user: vicanso 
  dbname: elite
  password: 123456
  sslmode: disable

# influxdb 配置
influxdb:
  uri: http://192.168.0.171:9991
  bucket: elite
  org: bigTree
  token: INFLUXDB_TOKEN 
  batchSize: 10

# session的相关配置
session:
  path: /
  key: elite
  ttl: 24h

# key for sign cookie
keys:
  - cuttlefish
  - secret

location:
  baseURL: http://172.18.109.188:7200/

# router limit
routerLimit:
  # 限制路由访问并发数
  GET /users/v1/me/login: 50

# mail相关配置
mail:
  host: smtp.office365.com
  port: 587
  user: tree.xie@outlook.com
  password: EMAIL_PASS

# 告警接收邮件列表
alarm:
  receiver:
  - tree.xie@outlook.com

# 卫斯理
wsl:
  baseURL: https://wsl520.com

# tiny服务
tiny:
  baseURL: http://127.0.0.1:6001