# 系统基本配置
basic:
  name: elite
  # 系统并发限制
  requestLimit: 1000
  listen: :7001
  prefixes:
  - /api

# 用户session的配置
session:
  path: /
  key: elite
  ttl: 240h
  # 用于加密session cookie 
  keys:
  - cuttlefish
  - secret
  trackKey: jt

# redis 配置
redis:
  # 可以配置为下面的形式，则从env中获取REDIS_URI对应的字符串来当redis连接串
  # uri: REDIS_URI
  # uri: redis://:pass@127.0.0.1:6379/?db=0&slow=200ms&maxProcessing=1000
  uri: redis://127.0.0.1:6379/?db=0&slow=200ms&maxProcessing=1000&prefix=elite

# postgres postgres配置
postgres:
  uri: postgresql://vicanso:A123456@127.0.0.1:5432/elite

# influxdb 配置
influxdb:
  uri: http://127.0.0.1:8086
  bucket: elite 
  org: bigTree
  token: AeSJbMPoFMmQ-tAaZdOefFZ8mIhe_TgxH8t0dMeBhKYmUyLZ8XOFCZsQqW8ptVflom6pgTlqYYiQUEUVMzgeYw==
  batchSize: 1000
  flushInterval: 10s
  disabled: false 

# mail相关配置
mail:
  host: smtp.office365.com
  port: 587
  user: tree.xie@outlook.com
  password: EMAIL_PASS

# 告警接收邮件列表
alarm:
  receivers:
  - tree.xie@outlook.com

# 定位相关配置
location:
  name: location
  timeout: 3s
  baseURL: https://ip.npmtrend.com

# minio配置
minio:
  endpoint: 127.0.0.1:9000
  accessKeyID: origin 
  secretAccessKey: test123456
  ssl: false

# tiny服务的配置
tiny:
  host: 192.168.1.2
  port: 6002
  timeout: 10s

# 抓取小说配置
novel:
  biquge:
    baseURL: https://www.biquge.com.cn
    timeout: 10s
  qidian:
    baseURL: https://www.qidian.com
    timeout: 10s