# production 生产环境中使用的相关配置

# influxdb 配置
influxdb:
  uri: http://172.18.109.188:9999

# key for sign cookie
keys:
  - 3YG6ah6C57
  - t98MYyGIgF

# redis 配置
redis: redis://:PASS@172.18.109.188:6379

# postgres 配置 (pass从env中获取pass这个配置为密码，如果未配置则为空)
postgres:
  host: 172.18.109.188
  password: PASS

# tiny服务
tiny:
  baseURL: http://172.18.109.188:7001