# production 生产环境中使用的相关配置

# redis 配置
redis: redis://:PASS@192.168.0.171:6379

# postgres 配置 (pass从env中获取pass这个配置为密码，如果未配置则为空)
postgres:
  host: 192.168.0.171
  password: PASS

# tiny服务
tiny:
  baseURL: http://192.168.0.171:7001