// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Configuration is the predicate function for configuration builders.
type Configuration func(*sql.Selector)

// NovelSource is the predicate function for novelsource builders.
type NovelSource func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserLogin is the predicate function for userlogin builders.
type UserLogin func(*sql.Selector)
